[package]
name = "easy_private_voting_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "master" , directory = "aztec" }
value_note = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "master" , directory = "value-note" }
safe_math = { git="https://github.com/AztecProtocol/aztec-nr", tag="aztec-packages-v0.19.0", directory="safe-math" }