[package]
name = "token_contract"
authors = [""]
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.17.0", directory="yarn-project/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.17.0", directory="yarn-project/aztec-nr/value-note" }
safe_math = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.17.0", directory="yarn-project/aztec-nr/safe-math" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.17.0", directory="yarn-project/aztec-nr/authwit" }
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.17.0", directory="yarn-project/noir-protocol-circuits/src/crates/types"}